# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ZSH CONFIG - ARCH CUSTOM

[[ $- != *i* ]] && return

source ~/.zinit/bin/zinit.zsh
zinit ice depth=1
zinit light romkatv/powerlevel10k
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions

[[ -f ~/.p10k.zsh ]] || PS1='[%n@%m %1~]$ '

alias ls='ls --color=auto'
alias kubectl="kubecolor"
alias nvim-kick="NVIM_APPNAME=kickstart nvim"
alias nvim-ide="NVIM_APPNAME=IDENvim nvim"
alias rust-nvim="NVIM_APPNAME=rust-nvim nvim"
alias general-nvim="NVIM_APPNAME=general-nvim nvim"
alias python-nvim="NVIM_APPNAME=python-nvim nvim"
alias golang-nvim="NVIM_APPNAME=golang-nvim nvim"

nvims() {
  items=("default" "general-nvim" "golang-nvim" "python-nvim" "rust-nvim" "IDENvim")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config 🖥️ " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim "$@"
}
bindkey -s '^B' 'nvims\n'

cat_csv() {
  cat "$1" | sed 's/,,/, ,/g' | column -t -s, | less -FXS
}

export GOPATH="$HOME/go"
export GOROOT="/usr/lib/go"
export PATH="$GOROOT/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/Dev/Project/github.com/TheTuxis/Erebor/EreborCli/target/release"
export PATH="$HOME/.local/bin:$PATH"

[[ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]] && source "$HOME/google-cloud-sdk/path.zsh.inc"
[[ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]] && source "$HOME/google-cloud-sdk/completion.zsh.inc"
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

clear

setopt autocd
setopt correct
setopt extended_glob
setopt hist_ignore_dups
setopt share_history
setopt no_beep
krabby random
