# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Ruta al archivo del historial
HISTFILE=~/.zsh_history

# Cantidad de comandos a guardar en memoria y archivo
HISTSIZE=10000         # en memoria
SAVEHIST=10000         # en disco

# Opciones para comportamiento del historial
setopt HIST_IGNORE_ALL_DUPS    # Ignora duplicados previos
setopt HIST_IGNORE_SPACE       # No guarda comandos que empiezan con espacio
setopt HIST_FIND_NO_DUPS       # Evita duplicados al buscar con flechas
setopt HIST_REDUCE_BLANKS      # Elimina espacios innecesarios
setopt SHARE_HISTORY           # Comparte el historial entre sesiones
setopt INC_APPEND_HISTORY      # Guarda cada comando en el archivo inmediatamente
setopt EXTENDED_HISTORY        # Guarda timestamps

touch ~/.zsh_history

# ZSH CONFIG - ARCH CUSTOM

[[ $- != *i* ]] && return

source ~/.zinit/bin/zinit.zsh
zinit ice depth=1
zinit light romkatv/powerlevel10k
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions

[[ -f ~/.p10k.zsh ]] || PS1='[%n@%m %1~]$ '

alias ls='ls --color=auto'
alias kubectl="kubecolor"
alias RustNvim="NVIM_APPNAME=RustNvim nvim"
alias GeneralNvim="NVIM_APPNAME=GeneralNvim nvim"
alias PythonNvim="NVIM_APPNAME=PythonNvim nvim"
alias GolangNvim="NVIM_APPNAME=GolangNvim nvim"

nvims() {
  items=("default" "GeneralNvim" "GolangNvim" "PythonNvim" "RustNvim")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config 🖥️ " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim "$@"
}
bindkey -s '^B' 'nvims\n'

cat_csv() {
  cat "$1" | sed 's/,,/, ,/g' | column -t -s, | less -FXS
}

export GOPATH="$HOME/go"
export GOROOT="/usr/lib/go"
export PATH="$GOROOT/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/Dev/Project/github.com/TheTuxis/Erebor/EreborCli/target/release"
export PATH="$HOME/.local/bin:$PATH"

[[ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]] && source "$HOME/google-cloud-sdk/path.zsh.inc"
[[ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]] && source "$HOME/google-cloud-sdk/completion.zsh.inc"
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

clear

setopt autocd
setopt correct
setopt extended_glob
setopt hist_ignore_dups
setopt share_history
setopt no_beep
krabby random
